eureka:
  client:
    service-url:
      defaultZone: http://domain-eureka:8761/eureka/

##将请求转发到对应模块进行处理
server:
  port: 9003
  servlet:
    context-path: /file
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
#配置本地上传文件路径
file:
  path: /Users/xiaozhe/Downloads/td/
  domain: http://127.0.0.1:9000/file/f/

